core/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from .views import SignUpView

app_name = "accounts"

urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(next_page="accounts:login"),
        name="logout",
    ),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("", include("django.contrib.auth.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/shortener/")),
    path("shortener/", include("shortener.urls")),
    path("accounts/", include("accounts.urls")),
]

core/shortener/urls.py
from django.urls import path
from . import views

app_name = "shortener"

urlpatterns = [
    path("", views.ShortenerListView.as_view(), name="list"),
    path("<int:pk>/", views.ShortenerDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.ShortenerDeleteView.as_view(), name="delete"),
    path("create/", views.ShortenerCreateView.as_view(), name="create"),
    path(
        "<str:short_url>",
        views.ShortenerRedirectView.as_view(),
        name="redirect",
    ),
]

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError(_("The email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    this is a custom User model for projects
    """

    email = models.EmailField(max_length=255, unique=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = "email"

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    objects = UserManager()

    def __str__(self):
        return self.email

core/shortener/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from .utils import generate_shortener_url

# getting USER model
User = get_user_model()


# Create your models here.
class Shortener(models.Model):
    """
    this is a class to define model of Shortener app
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    original_url = models.URLField()
    short_url = models.CharField(max_length=15, unique=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-create_date"]

    def __str__(self):
        return f"{self.original_url} to {self.short_url}"

    def clean(self):
        if Shortener.objects.filter(
            user=self.user, original_url=self.original_url
        ).exists():
            raise ValidationError("this URL is exists!")

    def save(self, *args, **kwargs):
        """
        overwrite save method
        """
        if not self.short_url:
            self.short_url = generate_shortener_url(self)
        self.full_clean()
        super().save(*args, **kwargs)

core/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as UserCreationBaseForm

User = get_user_model()


class UserCreationForm(UserCreationBaseForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")

core/shortener/forms.py
from django import forms
from .models import Shortener


class ShortenerForm(forms.ModelForm):
    class Meta:
        model = Shortener
        fields = ("original_url",)

    def clean_original_url(self):
        original_url = self.cleaned_data["original_url"]
        return original_url

core/accounts/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserCreationForm
from django.utils.translation import gettext_lazy as _


# Sign Up View
class SignUpView(SuccessMessageMixin, CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("accounts:login")
    template_name = "registration/signup.html"
    success_message = _("Your user was created successfully")

core/shortener/views.py
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponsePermanentRedirect
from .forms import ShortenerForm
from .models import Shortener


class ShortenerListView(LoginRequiredMixin, generic.ListView):
    """
    this is a class base view for List of Your URLs
    """

    model = Shortener
    paginate_by = 6

    def get_queryset(self):
        return Shortener.objects.filter(user=self.request.user)


class ShortenerDetailView(LoginRequiredMixin, generic.DetailView):
    """
    this is a class base view for Detail of Your URL
    """

    model = Shortener

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class ShortenerCreateView(LoginRequiredMixin, generic.CreateView):
    """
    this is a class base view for Creation New URL
    """
    model = Shortener
    form_class = ShortenerForm
    template_name = "shortener/shortener_create.html"
    success_url = reverse_lazy("shortener:list")

    def form_valid(self, form):
        original_url = form.instance.original_url

        if Shortener.objects.filter(
            original_url=original_url, user=self.request.user
        ).exists():
            form.add_error(None, "This url is exist")
            return super().form_invalid(form)

        form.instance.user = self.request.user
        return super().form_valid(form)


class ShortenerDeleteView(LoginRequiredMixin, generic.DeleteView):
    """
    this is a class base view for Delete for once URL
    """
    model = Shortener
    success_url = reverse_lazy("shortener:list")


class ShortenerRedirectView(LoginRequiredMixin, View):
    """
    this is a class base view for Redirect URL
    """

    def get(self, request, short_url, *args, **kwargs):
        obj = get_object_or_404(Shortener, short_url=short_url)
        return HttpResponsePermanentRedirect(obj.original_url)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>


    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <a class="navbar-brand" href="#">URL Shortener</a>
        <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-target="#navbarNav" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'shortener:list' %}">My URLs</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'shortener:create' %}">Create URL</a>
                {% endif %}
            </li>
        </ul>
    </div>

    {% if user.is_authenticated %}
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">User - {{ user.email }}</a>
        <button class="navbar-toggler" data-target=".dual-collapse2" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">

                <a class="nav-link bi bi-box-arrow-in-right" href="{% url 'accounts:logout' %}"> LogOut</a>
            </li>
        </ul>
    </div>


    {% else %}
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
        </ul>
    </div>

    {% endif %}
</nav>

{% block body %}


{% endblock body %}
</body>

{% load static %}
<script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>

{% block extra_js %}
{% endblock extra_js %}

</html>

core/templates/shortener/shortener_create.html
{% extends 'base.html' %}

{% block title %}
Create New URL
{% endblock title %}

{% block body %}

<div class="container">
    <div class="card mt-5">
        <div class="card-header text-center py-3">
            <h1>URL Shortener Application <i class="fas fa-link px-2"></i></h1>
        </div>
        <div class="px-3 py-4">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row g-1 justify-content-md-center">
                    <div class="col-8">
                        <input type="url" class="form-control rounded-4 h-100" id="{{form.original_url}}">
                    </div>
                    <div class="col-2">
                        <button class="btn btn-primary w-100 h-100" type="submit">
                            Generate
                        </button>
                    </div>
                </div>
            </form>


            {% if form.non_field_errors %}
            <div class="alert alert-danger mt-4" role="alert">
                <p>{{form.non_field_errors}}</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock body %}

core/templates/shortener/shortener_detail.html
{% extends 'base.html' %}

{% block title %}
Detail URL
{% endblock title %}

{% block body %}
{% load static %}
<script src="{% static 'js/shortener/shortener_detail.js' %}"></script>

{% csrf_token %}
<div class="container mx-auto mt-5 p-2">
    <table class="table table-striped">
        <tbody>
        <tr>
            <th scope="row" style="width:200px;">User</th>
            <td>{{ object.user }}</td>
        </tr>
        <tr>
            <th scope="row">Original URL</th>
            <td>{{ object.original_url }}</td>
        </tr>
        <tr>
            <th scope="row">Short URL</th>
            <td>{{ object.short_url }}</td>
        </tr>
        <tr>
            <th scope="row">Create Time</th>
            <td>{{ object.create_date }}</td>
        </tr>
        </tbody>
    </table>
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <input data-url="{% url 'shortener:delete' pk=object.pk %}" id="url" type="hidden"/>
            <input data-url="{% url 'shortener:list' %}" id="url-success" type="hidden"/>
            <a class="btn btn-danger" id="delete" onclick="deleteClick()" type="button"><i class="bi bi-trash"></i></a>
            <a class="btn btn-primary" href="{% url 'shortener:redirect' short_url=object.short_url %}" id="link"
               target="_blank" type="button"><i
                    class="bi bi-link-45deg"></i></a>
        </div>

    </div>
</div>

{% endblock body %}

core/templates/shortener/shortener_list.html
{% extends 'base.html' %}

{% block title %}
My URLs
{% endblock title %}

{% block body %}

{% load static %}
<script src="{% static 'js/shortener/shortener_list.js' %}"></script>


<div class="container mt-5">
    <!--  <span id="total" value="{{ object_list|length }}">Total Item {{ object_list|length }}</span>-->
    <ul class="list-group list-group-flush">
        {% csrf_token %}
        {% for obj in object_list %}
        <li class="list-group-item">

            <div class="input-group">
                <a class="btn btn-primary" href="{% url 'shortener:detail' pk=obj.id %}" id="detail-{{forloop.counter0}}"
                   type="button">
                    show
                    <div>
                        <span class="bi bi-eye"></span>
                    </div>
                </a>
                <ul class="form-control">
                    <li class="list-group-item">{{obj.original_url}}</li>
                    <li class="list-group-item">{{ request.get_host }}/shortener/{{obj.short_url}}</li>
                </ul>
<!--                <span class="form-control" type="text"></span>-->
                <div class="p-4 justify-content-md-center">
                    <input data-url="{% url 'shortener:delete' pk=obj.pk %}" id="url-{{forloop.counter0}}"
                           type="hidden"/>
                    <a class="btn btn-danger" id="delete-{{forloop.counter0}}" name="{{forloop.counter0}}" onclick="deleteClick(this.name)"
                       type="button"><i class="bi bi-trash"></i></a>
                    <a class="btn btn-primary" href="{% url 'shortener:redirect' short_url=obj.short_url %}" id="link-{{forloop.counter0}}"
                       target="_blank" type="button"><i
                            class="bi bi-link-45deg"></i></a>
                </div>
            </div>
        </li>
        {% endfor %}

    </ul>
    {% if object_list|length %}
    <nav aria-label="..." class="mt-5">

        <ul class="pagination justify-content-center">
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">

                <a class="page-link"
                   href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% endif %}">Previous</a>

            </li>
            <li aria-current="page" class="page-item active">
      <span class="page-link">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>
            </li>

            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">

                <a class="page-link"
                   href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% endif %}">Next</a>

            </li>

        </ul>

    </nav>
    {% else %}
    <div class="justify-content-center mx-auto" style="width:200px;">
        <h3 >Items not found!</h3>
    </div>
        {% endif %}

</div>

{% endblock body %}